module.exports.insert = require('./insert')
module.exports.get = require('./get')
module.exports.update = require('./update')
module.exports.delete = require('./delete')
module.exports.download = require('./download')
